Add tendency terms
E3SM-Project/Omega pull request #92
Opened 2024-06-11 22:57 UTC by brian-oneill

This PR adds functors for tendency terms necessary to solve the shallow water equations. Some arrays utilized by these functors have also been added to the HorzMesh class. Functors for all the terms in the momentum, layer thickness, and tracer equations are included. Unit tests for most of the terms on planar and spherical mesh configurations have been implemented and tested.

This is a draft, TODO:
- Documentation, dev guide, user guide and commenting code files
- Analytical solutions needed by unit tests for VelDiff and VelHyperDiff functors on spherical mesh
- Unit tests for tendency terms of the tracer equation

Checklist
* [ ] Documentation:
  * [ ] Design document has been generated and added to the docs
  * [ ] User's Guide has been updated
  * [ ] Developer's Guide has been updated
  * [ ] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [ ] Testing
  * [ ] CTest unit tests for new features have been added per the approved design. 
  * [ ] Unit tests have passed. Please provide a relevant CDash build entry for verification.

2024-06-21 13:46 UTC, mark-petersen commented
@brian-oneill please provide the files you used to run your tests. ctest is looking for the files
```
test/OmegaPlanarMesh.nc   test/OmegaSphereMesh.nc
```
and I gave it some standard files but it fails.

2024-06-21 15:17 UTC, xylar commented
@mark-petersen, the 3 meshes in https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/ are what I use in the polaris ctest utility. Try those.

2024-06-21 15:55 UTC, xylar commented
Specifically:
```
cd test
wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/ocean.QU.240km.151209.nc
ln -s ocean.QU.240km.151209.nc OmegaMesh.nc
wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/cosine_bell_icos480_initial_state.230220.nc
ln -s cosine_bell_icos480_initial_state.230220.nc OmegaSphereMesh.nc
wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/PlanarPeriodic48x48.nc
ln -s PlanarPeriodic48x48.nc OmegaPlanarMesh.nc
```

2024-06-25 22:44 UTC, mwarusz requested changes
I know that this PR is still a work in progress, but I had a couple of suggestion based in my initial reading.

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +                             NormRVortEdge(JEdge, K) + NormFEdge(JEdge, K)) * 0.5;
```suggestion
                             NormRVortEdge(JEdge, K) + NormFEdge(JEdge, K)) * 0.5_Real;
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      const Real InvDcEdge = 1. / DcEdge(IEdge);
```suggestion
      const Real InvDcEdge = 1._Real / DcEdge(IEdge);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      const Real DvEdgeInv = 1. / DvEdge(IEdge);
```suggestion
      const Real DcEdgeInv = 1._Real / DcEdge(IEdge);
      const Real DvEdgeInv = 1._Real / DvEdge(IEdge);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      const Real DvEdgeInv = 1. / DvEdge(IEdge);
```suggestion
      const Real DcEdgeInv = 1._Real / DcEdge(IEdge);
      const Real DvEdgeInv = 1._Real / DvEdge(IEdge);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +                (NormTrCell(L, JCell0, K) + NormTrCell(L, JCell1, K)) * 0.5;
```suggestion
                (NormTrCell(L, JCell0, K) + NormTrCell(L, JCell1, K)) * 0.5_Real;
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      Real InvAreaCell = 1. / AreaCell(ICell);
```suggestion
      Real InvAreaCell = 1._Real / AreaCell(ICell);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +         const Real InvDcEdge = 1. / DcEdge(JEdge);
```suggestion
         const Real InvDcEdge = 1._Real / DcEdge(JEdge);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      Real InvAreaCell = 1. / AreaCell(ICell);
```suggestion
      Real InvAreaCell = 1._Real / AreaCell(ICell);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +      Real InvAreaCell = 1. / AreaCell(ICell);
```suggestion
      Real InvAreaCell = 1._Real / AreaCell(ICell);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/src/ocn/TendencyTerms.h
> +         const Real InvDcEdge = 1. / DcEdge(JEdge);
```suggestion
         const Real InvDcEdge = 1._Real / DcEdge(JEdge);
```

2024-06-25 22:44 UTC, mwarusz commented on components/omega/test/ocn/TendencyTermsTest.cpp
> +
```suggestion
return Err;
```

2024-07-08 21:16 UTC, mark-petersen commented on components/omega/doc/userGuide/TendencyTerms.md
> +| SSHGradONEdge | gradient of sea-surface height, multipled of gravitational acceleration, defined on edges
```suggestion
| SSHGradOnEdge | gradient of sea-surface height, multiplied by gravitational acceleration, defined on edges
```

2024-07-09 00:57 UTC, hyungyukang approved these changes
@brian-oneill , Everything looks good to me. Thank you for your efforts on this. I've tested this PR by implementing a shallow water model, where the tendency terms are computed by this PR. As expected, the convergence rate with horizontal resolutions exactly follows the second-order slope (tested with the nonlinear manufactured solution), indicating that all computations from this PR, as well as auxiliary variable computations (#90), are accurate:

<img width="485" alt="image" src="https://github.com/E3SM-Project/Omega/assets/47987430/e7862a35-a64d-454b-ae0e-cb8070b4101c">

I'm approving this PR, but there are two things I would liked to comment for the future reference:
- The gravity acceleration is now hardcoded as 9.80665, but it should be changed by Config or the upper-level driver in the future.
- In `SSHGradOnEdge`, `HCell` is actually `h-b`. The `BottomDepth (b)` could be included in the `SSHGradOnEdge`, or the total depth can be updated before computing `SSHGradOnEdge`.

2024-07-09 12:38 UTC, philipwjones approved these changes
I have not checked correctness, but looks like others have. Just a couple of minor things to change.

I suspect we are going to need to break this up eventually to prevent it from becoming a single 200k LOC routine, but that can maybe be done in a later PR.

2024-07-09 12:38 UTC, philipwjones commented on components/omega/src/ocn/HorzMesh.cpp
> +             o_EdgeMask(Edge, K) = 1.0;
These o_ arrays should follow the naming conventions using a CamelCase name starting with a capital letter.

2024-07-09 12:38 UTC, philipwjones commented on components/omega/test/ocn/TendencyTermsTest.cpp
> +int main(int argc, char *argv[]) {
With recent changes to the testing, we require main to actually return the error code, so you'll want to have tendencyTermsTest to return Err and then main return that Err as an exit code. This was to catch certain errors that didn't create a FAIL but caused the code to exit.

2024-07-09 23:10 UTC, mark-petersen approved these changes
Approving based on ctest results and @hyungyukang's testing above.

2024-07-15 15:40 UTC, mwarusz approved these changes
LGTM

2024-07-17 18:55 UTC, kieran-ringel commented
![image](https://github.com/user-attachments/assets/5220bd31-62b6-4304-895a-852e217c22cc)
![image](https://github.com/user-attachments/assets/032c1ade-b034-4887-9880-c1d4c9558ed9)
![image](https://github.com/user-attachments/assets/90f8c0d5-c0cc-48dc-a81d-b75e66d9d601)
I've tested this PR by adding C++ timers around the ParallelFor for each tendency term and a loop to perform the ParallelFor 10 times to get larger timing values. 
`   auto t1 = std::chrono::system_clock::now();
   for(int i = 0; i < 10; i++){
   parallelFor(
      {Mesh->NCellsOwned, NVertLevels}, KOKKOS_LAMBDA(int ICell, int KLevel) {
         ThickFluxDivOnC(NumThickFluxDiv, ICell, KLevel, ThickFluxEdge);
      });
   }
   auto t2 = std::chrono::system_clock::now();
   std::chrono::duration<double> ellapsed = t2 - t1;
   std::cout << "ThickFluxDivTiming " << ellapsed.count() << "\n";`
Convergence tests were done by getting the L2 and LInf error values, these test did not loop over the ParallelFor additional times.

2024-07-17 19:00 UTC, kieran-ringel commented
To confirm the resulting values in the exact and numeric results I output the .nc file, I did this using Omega's IO.
`/*
   OMEGA::Decomp *DefDecomp = OMEGA::Decomp::getDefault();

  std::vector<int> OffsetEdge(Mesh->NEdgesSize * NVertLevels, -1);
  for (int Edge = 0; Edge < Mesh->NEdgesOwned; ++Edge) {
        int GlobalEdgeAdd = DefDecomp->EdgeIDH(Edge) - 1;
        for (int k = 0; k < NVertLevels; ++k) {
           int VectorAdd         = Edge * NVertLevels + k;
           OffsetEdge[VectorAdd] = GlobalEdgeAdd * NVertLevels + k;
        }
     }


  int DecompEdgeR8;
  std::vector<int> EdgeDims{DefDecomp->NEdgesGlobal, NVertLevels};
  int EdgeArraySize = Mesh->NEdgesSize * NVertLevels;
  OMEGA::IO::createDecomp(DecompEdgeR8, OMEGA::IO::IOTypeR8, 2,
                                   EdgeDims, EdgeArraySize, OffsetEdge,
                                   OMEGA::IO::DefaultRearr);


  int OutFileID;
  OMEGA::IO::openFile(
        OutFileID, "ThickFluxTest.nc", OMEGA::IO::ModeWrite, OMEGA::IO::FmtDefault,
        OMEGA::IO::IfExists::Replace, OMEGA::IO::Precision::Double);


  int DimEdgeID;
  int DimVertID;
  OMEGA::IO::defineDim(OutFileID, "NVertLevels", NVertLevels, DimVertID);
  OMEGA::IO::defineDim(OutFileID, "NEdges", DefDecomp->NEdgesGlobal, DimEdgeID);


  int VarIDEdgeExact;
  int EdgeDimIDs[2] = {DimEdgeID, DimVertID};
  OMEGA::IO::defineVar(OutFileID, "Exact", OMEGA::IO::IOTypeR8, 2,
                                EdgeDimIDs, VarIDEdgeExact);
    
  int VarIDEdgeComputed;
  OMEGA::IO::defineVar(OutFileID, "Computed", OMEGA::IO::IOTypeR8, 2,
                                EdgeDimIDs, VarIDEdgeComputed);
*/
   // Compute exact result
   Array2DReal ExactThickFluxDiv("ExactThickFluxDiv", Mesh->NCellsOwned,
                                 NVertLevels);

   //OMEGA::R8 Fill = -1.23456789e30;
   //OMEGA::IO::writeArray(ExactThickFluxDiv.data(), Mesh->NEdgesSize * NVertLevels, &Fill, OutFileID, DecompEdgeR8, VarIDEdgeExact);
OMEGA::IO::closeFile(OutFileID);`

2024-07-17 20:57 UTC, mark-petersen commented
I tested this branch one more time with CPUs and GPUs on perlmutter. Here are my instructions:

<details>
<summary> CPU on perlmutter </summary> <p>

```
cd /global/homes/m/mpeterse/repos/omega/develop
git fetch
git reset --hard origin/develop
git submodule update --init --recursive externals/ekat externals/scorpio cime
cd components/omega/

module load cmake
DIR=240715_omega_cpu
mkdir ${PSCRATCH}/runs/$DIR
cd !$

rm -rf build
mkdir build
cd build
export PARMETIS_ROOT=/global/cfs/cdirs/e3sm/software/polaris/pm-cpu/spack/dev_polaris_0_3_0_gnu_mpich/var/spack/environments/dev_polaris_0_3_0_gnu_mpich/.spack-env/view
cmake \
   -DOMEGA_CIME_COMPILER=gnu  \
   -DOMEGA_CIME_MACHINE=pm-cpu \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S /global/homes/m/mpeterse/repos/omega/pr_tendterms_boneill/components/omega -B .
./omega_build.sh

# linking:
cd test
ln -isf /global/homes/m/mpeterse/meshes/omega/O*nc .
# note, original files from here:
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/ocean.QU.240km.151209.nc
# ln -s ocean.QU.240km.151209.nc OmegaMesh.nc
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/cosine_bell_icos480_initial_state.230220.nc
# ln -s cosine_bell_icos480_initial_state.230220.nc OmegaSphereMesh.nc
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/PlanarPeriodic48x48.nc
# ln -s PlanarPeriodic48x48.nc OmegaPlanarMesh.nc

# run test:
salloc --nodes 1 --qos interactive --time 01:00:00 --constraint cpu --account=m4572 # or e3sm
DIR=240715_omega_cpu
cd ${PSCRATCH}/runs/${DIR}/build

./omega_ctest.sh

also:
./omega_ctest.sh -R TEND_PLANE_TEST

# output in Testing/Temporary/LastTest.log
```
</details>

<details>
<summary> GPU on perlmutter </summary> <p>

```

DIR=240715_omega_gpu
mkdir ${PSCRATCH}/runs/$DIR
cd !$

rm -rf build
mkdir build
cd build
PARMETIS_ROOT=/global/cfs/cdirs/e3sm/software/polaris/pm-gpu/spack/dev_polaris_0_3_0_gnugpu_mpich/var/spack/environments/dev_polaris_0_3_0_gnugpu_mpich/.spack-env/view
module load cmake
cmake \
   -DOMEGA_CIME_COMPILER=gnugpu  \
   -DOMEGA_CIME_MACHINE=pm-gpu \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S /global/homes/m/mpeterse/repos/omega/pr_tendterms_boneill/components/omega -B .
./omega_build.sh

# linking:
cd test
ln -isf /global/homes/m/mpeterse/meshes/omega/O*nc .
# note, original files from here:
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/ocean.QU.240km.151209.nc
# ln -s ocean.QU.240km.151209.nc OmegaMesh.nc
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/cosine_bell_icos480_initial_state.230220.nc
# ln -s cosine_bell_icos480_initial_state.230220.nc OmegaSphereMesh.nc
# wget https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/omega_ctest/PlanarPeriodic48x48.nc
# ln -s PlanarPeriodic48x48.nc OmegaPlanarMesh.nc

# run test:
salloc --nodes 4 --qos interactive --time 01:00:00 --constraint gpu --tasks-per-node=2 --gpus-per-task 1 --account=m4572_g # or e3sm_g
DIR=240715_omega_gpu
cd ${PSCRATCH}/runs/${DIR}/build

./omega_ctest.sh

```

Passes all 17 tests on both.
</details>

2024-07-18 21:49 UTC, merged